import globals from 'globals';

import stylistic from '@stylistic/eslint-plugin';

export default [
	{
		plugins: {
			'@stylistic': stylistic,
		},
		languageOptions: {
			globals: {
				...globals.browser,
			},
		},
		rules: {
			'prefer-const': 'warn',
			'for-direction': 'error',
			'getter-return': 'error',
			'no-cond-assign': ['warn', 'always'],
			'no-const-assign': 'error',
			'no-constant-binary-expression': 'warn',
			'no-constant-condition': 'warn',
			'no-constructor-return': 'warn',
			'no-debugger': 'warn',
			'no-dupe-args': 'error',
			'no-dupe-class-members': 'error',
			'no-dupe-else-if': 'warn',
			'no-dupe-keys': 'error',
			'no-duplicate-case': 'error',
			'no-await-in-loop': 'warn',
			'array-callback-return': 'warn',
			'no-duplicate-imports': 'error',
			'no-empty-character-class': 'warn',
			'no-empty-pattern': 'error',
			'no-ex-assign': 'error',
			'no-class-assign': 'error',
			'no-fallthrough': ['warn', { allowEmptyCase: true }],
			'no-func-assign': 'error',
			'no-import-assign': 'error',
			'no-inner-declarations': ['error', 'both'],
			'no-invalid-regexp': 'error',
			'no-irregular-whitespace': ['warn', { skipComments: true, skipRegExps: true, skipTemplates: true }],
			'no-loss-of-precision': 'warn',
			'no-misleading-character-class': 'warn',
			'no-new-native-nonconstructor': 'error',
			'no-obj-calls': 'error',
			'no-promise-executor-return': 'warn',
			'no-prototype-builtins': 'warn',
			'no-self-assign': 'error',
			'no-self-compare': 'warn',
			'no-setter-return': 'warn',
			'no-sparse-arrays': 'warn',
			'no-template-curly-in-string': 'warn',
			'no-this-before-super': 'warn',
			'no-undef': 'error',
			'constructor-super': 'error',
			'no-unexpected-multiline': 'error',
			'no-unmodified-loop-condition': 'warn',
			'no-unreachable': 'warn',
			'no-unreachable-loop': 'warn',
			'no-unsafe-negation': 'error',
			'no-unsafe-optional-chaining': 'error',
			'no-unused-private-class-members': 'error',
			'no-unused-vars': ['warn', { args: 'after-used', caughtErrors: 'none' }],
			'no-unsafe-finally': 'warn',
			'no-use-before-define': 'error',
			'no-useless-assignment': 'warn',
			'no-useless-backreference': 'warn',
			'require-atomic-updates': 'warn',
			'use-isnan': 'error',
			'valid-typeof': 'error',
			'arrow-body-style': ['warn', 'as-needed'],
			'block-scoped-var': 'error',
			'consistent-return': 'error',
			'curly': 'error',
			'default-case': 'warn',
			'default-case-last': 'error',
			'default-param-last': 'error',
			'dot-notation': 'warn',
			'eqeqeq': 'warn',
			'func-name-matching': 'warn',
			'func-style': ['warn', 'declaration'],
			'guard-for-in': 'warn',
			'init-declarations': ['error', 'always'],
			'logical-assignment-operators': ['warn', 'always'],
			'new-cap': ['warn', { newIsCap: true, capIsNew: true }],
			'no-array-constructor': 'warn',
			'no-caller': 'error',
			'no-case-declarations': 'error',
			'no-console': 'warn',
			'no-delete-var': 'error',
			'no-else-return': ['error', { allowElseIf: false }],
			'no-empty': 'warn',
			'no-empty-static-block': 'warn',
			'no-extra-bind': 'warn',
			'no-extra-boolean-cast': 'warn',
			'no-extra-label': 'warn',
			'no-global-assign': 'error',
			'no-implicit-coercion': 'warn',
			'no-implied-eval': 'warn',
			'no-invalid-this': 'error',
			'no-iterator': 'error',
			'no-label-var': 'error',
			'no-lone-blocks': 'warn',
			'no-multi-assign': 'error',
			'no-nested-ternary': 'warn',
			'no-new-func': 'error',
			'no-new-wrappers': 'warn',
			'no-object-constructor': 'warn',
			'no-octal': 'warn',
			'no-plusplus': 'error',
			'no-proto': 'error',
			'no-redeclare': 'error',
			'no-shadow': 'error',
			'no-throw-literal': 'error',
			'no-unneeded-ternary': 'warn',
			'no-unused-expressions': 'warn',
			'no-unused-labels': 'warn',
			'no-useless-call': 'warn',
			'no-useless-catch': 'warn',
			'no-useless-computed-key': 'warn',
			'no-useless-concat': 'warn',
			'no-useless-constructor': 'warn',
			'no-useless-escape': 'warn',
			'no-useless-rename': 'warn',
			'no-useless-return': 'warn',
			'no-var': 'error',
			'no-void': 'error',
			'no-with': 'error',
			'one-var': ['warn', 'never'],
			'prefer-exponentiation-operator': 'warn',
			'prefer-object-spread': 'warn',
			'prefer-rest-params': 'error',
			'prefer-spread': 'error',
			'prefer-template': 'warn',
			'require-await': 'warn',
			'require-yield': 'warn',
			'symbol-description': 'warn',

			'@stylistic/array-bracket-newline': ['warn', 'consistent'],
			'@stylistic/array-bracket-spacing': ['warn', 'never'],
			'@stylistic/array-element-newline': ['warn', 'consistent'],
			'@stylistic/func-call-spacing': ['warn', 'never'],
			'@stylistic/arrow-parens': ['warn', 'as-needed'],
			'@stylistic/arrow-spacing': 'warn',
			'@stylistic/block-spacing': 'warn',
			'@stylistic/brace-style': ['warn', 'stroustrup'],
			'@stylistic/comma-dangle': ['warn', 'always-multiline'],
			'@stylistic/comma-spacing': ['warn', { before: false, after: true }],
			'@stylistic/comma-style': ['warn', 'last'],
			'@stylistic/computed-property-spacing': ['warn', 'never'],
			'@stylistic/curly-newline': ['warn', { consistent: true }],
			'@stylistic/dot-location': ['warn', 'property'],
			'@stylistic/eol-last': ['warn', 'always'],
			'@stylistic/function-call-spacing': ['warn', 'never'],
			'@stylistic/function-call-argument-newline': ['warn', 'consistent'],
			'@stylistic/generator-star-spacing': ['error', { before: false, after: true }],
			'@stylistic/implicit-arrow-linebreak': ['error', 'beside'],
			'@stylistic/indent': ['warn', 'tab'],
			'@stylistic/indent-binary-ops': ['warn', 'tab'],
			'@stylistic/key-spacing': ['warn', { beforeColon: false, afterColon: true, mode: 'strict' }],
			'@stylistic/keyword-spacing': ['warn', { before: true, after: true }],
			'@stylistic/lines-between-class-members': ['warn', 'always'],
			'@stylistic/new-parens': 'error',
			'@stylistic/no-confusing-arrow': 'warn',
			'@stylistic/no-extra-semi': 'warn',
			'@stylistic/no-floating-decimal': 'error',
			'@stylistic/no-mixed-operators': 'warn',
			'@stylistic/no-mixed-spaces-and-tabs': 'warn',
			'@stylistic/no-multi-spaces': 'warn',
			'@stylistic/no-trailing-spaces': 'warn',
			'@stylistic/no-whitespace-before-property': 'warn',
			'@stylistic/object-curly-newline': ['warn', { consistent: true }],
			'@stylistic/object-curly-spacing': ['warn', 'never'],
			'@stylistic/object-property-newline': ['warn', { allowAllPropertiesOnSameLine: true }],
			'@stylistic/operator-linebreak': ['warn', 'before'],
			'@stylistic/padded-blocks': ['warn', 'never'],
			'@stylistic/padding-line-between-statements': ['warn', { blankLine: 'always', prev: '*', next: '*' }],
			'@stylistic/quote-props': ['warn', 'consistent-as-needed'],
			'@stylistic/quotes': ['warn', 'single'],
			'@stylistic/rest-spread-spacing': ['warn', 'never'],
			'@stylistic/semi': ['error', 'always'],
			'@stylistic/semi-spacing': 'warn',
			'@stylistic/semi-style': ['error', 'last'],
			'@stylistic/space-before-blocks': 'warn',
			'@stylistic/space-before-function-paren': ['warn', { anonymous: 'never', named: 'never', asyncArrow: 'always' }],
			'@stylistic/space-in-parens': ['warn', 'never'],
			'@stylistic/space-infix-ops': 'warn',
			'@stylistic/space-unary-ops': 'warn',
			'@stylistic/switch-colon-spacing': 'warn',
			'@stylistic/template-curly-spacing': 'warn',
			'@stylistic/template-tag-spacing': 'warn',
			'@stylistic/wrap-iife': ['warn', 'inside'],
			'@stylistic/yield-star-spacing': ['warn', 'after'],
		},
	},
];
